version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      
  db:
    image: postgres:13-alpine
    volumes:
      - ./db_data/:/var/lib/postgresql/data/
    ports:
      - '27017:27017'
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"