version: '3.8'

services:
  web:
    build: .
    # command: uvicorn app.main:app --host 0.0.0.0
    command: bash -c 'while !</dev/tcp/database/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --reload'

    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - database
      
  database:
    image: postgres:13-alpine
    volumes:
      - ./db_data/:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  db_data:
